### ISSUE TITLE
Can't see logs in portainer.

### ISSUE THREAD

**Issue by luluhoc** [bubuntux/nordlynx#103]
### **Describe the bug**
Can't see logs in portainer it gives me the error.

```

Failure
Expected property name or '}' in JSON at position 1

```

**Comment by pbarone** [comment]
same problem when trying to see the logs in portainer:
Failure
JSON.parse: end of data while reading object contents at line 1 column 2 of the JSON data

**Comment by sam-semillia** [comment]
Same problem here. However, if you run the container in Host mode, the logs can be displayed in portainer, but NO connection to NordVPN can be created then.
