### ISSUE TITLE
login wont work

### ISSUE THREAD

**Issue by bsession1014** [bubuntux/nordlynx#125]
this is the same for the nordvpn docker on unraid as well as nordlynx on unraid. says that nordvpn has an update and that log in is incorrect i have tryed many diffrent ways from putting on MFA to turn it back off to changing the password to trying the Service credentials (manual setup) user name and pass word i also trid changing the get private key comand to use token i think it almost got somewhare but it said something that it wasent reachable in the docker config i think. i hope this is helpfull i really enjoy your work.

**Comment by bubuntux** [comment]
to use this image you need to get the private key using the a token ad follow the instructions on the readme, once you have the private key, you need to post what commands are you trying and what errors are you getting in order to properly get help

**Comment by slagiewka** [comment]
Make sure to re-pull
```sh
docker pull ghcr.io/bubuntux/nordvpn:get_private_key
```

(if you've been previously using the image) so that you're on `sha256:0d91aabb4511d400b01e930654950729a4e859d3c250f61664662b0ed7027c56`. Then running with access token ([from the Services > NordVPN](https://my.nordaccount.com/dashboard/nordvpn/)) should work again.

**Comment by bsession1014** [comment]
can confirm im back up and going i moved to nordlynx with token way easyer thank you by the way but up and going fast now
