### ISSUE TITLE
Unable to Specify Specific Server in Config

### ISSUE THREAD

**Issue by SpekOregonian** [bubuntux/nordlynx#132]
When specifying a specific server public key, the parameter is ignored and server is auto selected. 

cont-init: info: /etc/cont-init.d/10-validate exited 0
cont-init: info: running /etc/cont-init.d/20-inet
[2023-05-17T08:40:47-04:00] Enabling connection to eth0 172.17.0.2/16
[2023-05-17T08:40:47-04:00] Enabling connection to secure interfaces
cont-init: info: /etc/cont-init.d/20-inet exited 0
cont-init: info: running /etc/cont-init.d/20-inet6
[2023-05-17T08:40:47-04:00] No interface network6 detected
cont-init: info: /etc/cont-init.d/20-inet6 exited 0
cont-init: info: running /etc/cont-init.d/30-route
[2023-05-17T08:40:47-04:00] Enabling connection to network 192.168.1.0/24
cont-init: info: /etc/cont-init.d/30-route exited 0
cont-init: info: running /etc/cont-init.d/30-route6
cont-init: info: /etc/cont-init.d/30-route6 exited 0
cont-init: info: running /etc/cont-init.d/40-allowlist
cont-init: info: /etc/cont-init.d/40-allowlist exited 0
[custom-init] No custom files found, skipping...
services-up: info: copying legacy longrun wireguard (no readiness notification)
[ls.io-init] done.
[2023-05-17T08:40:47-04:00] Finding the best server...
[2023-05-17T08:40:47-04:00] Using server: {

**Comment by SpekOregonian** [comment]
I would also like to mention traffic fails to pass through VPN when PUBLIC_KEY is defined. I had to remove the entry to get traffic to pass.

**Comment by SpekOregonian** [comment]
Also, attempting to specify IP via END_POINT fails as no port is specified. Attempted to set via END_POINT_PORT but that doesn't seem to be the value to assign.

[2023-05-17T12:05:43-04:00] Connecting...
[#]                                
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63 
Unable to find port of endpoint: `153.92.40.126'
Configuration parsing error   
[#] ip link delete dev wg0

**Comment by TuaTime1** [comment]
Not sure what you are doing differently but I have public key, private key and end point set up and everything works fine.  I use the endpoint domain, not the ip.
