### ISSUE TITLE
Trying to get wireguard private key and end up with 'whoops! /run/nordvpn/nordvpnd.sock not found'

### ISSUE THREAD

**Issue by jcmschwa** [bubuntux/nordlynx#145]
### **Describe the bug**
When following the directions outlined here (https://github.com/bubuntux/nordlynx#how-to-get-your-private_key) 
`Waiting for daemon to start up...
Whoops! /run/nordvpn/nordvpnd.sock not found.
Invalid token. ¯\_(ツ)_/¯`

### **To Reproduce using docker CLI**
Full command needs to be provided (hide credentials)
`sudo docker run --rm --cap-add=NET_ADMIN -e TOKEN=[[redacted]] ghcr.io/bubuntux/nordvpn:get_private_key`

### **Expected behavior**
Per the directions, I believe I should receive my wireguard private key.

### **Logs**
n/a

### **Additional context**
Attempting on Synology DS920+.

**Comment by pquinn1212** [comment]
im also getting this when running on unraid

**Comment by jvince11** [comment]
Also got this on Synology `DSM 7.2-64570 Update 1`, and confirmed the same `docker run` command on my fedora server 38 x86_64 intel machine works as expected.

**Comment by TheWhiteWarlock** [comment]
Having trouble as well:

Waiting for daemon to start up...
A new version of NordVPN is available! Please update the application.
It's not you, it's us. We're having trouble reaching our servers. If the issue persists, please contact our customer support.
Invalid token. ¯\_(ツ)_/¯

**Comment by b-kamphorst** [comment]
I had the same issue. This is not a fix per se, but it might help you to get your private key. The instructions below assume that NordVPN is running in Windows.

1. Install WireGuard for Windows.
2. Connect to some server through the NordVPN GUI.
  - I temporarily forced the VPN protocol to NordLynx in the GUI settings.
3. Open Windows CMD with elevated rights.
4. Run the following command: `wg show NordLynx private-key` and get your private key!
  - For me, `NordLynx` is the name of the interface listed under `interface` when executing the plain command `wg`. I expect this to be the same for others, but if the command doesn't work then please verify the interface name.

I unsuccessfully tried many other things (through WSL2, through Synology NAS), but in the end this gave me a key. Hope this helps for others!
