### ISSUE TITLE
Ability to set which location to connect to

### ISSUE THREAD

**Issue by adamef93** [bubuntux/nordlynx#149]
**Describe the solution you'd like**
I have a nordlynx container running in one of my stacks with a SERVERURL variable using the url of a local node to reduce latency. I tried deploying the same config in a different stack using a node url in a different location and it still connected to something local, if not the same node. Confirmed by comparing the geoIP results of the IP assigned to the container vs an IP received by selecting the same location in the Nord desktop app. I wouldn't have just added a SERVERURL to the stack myself which makes me think this option existed at one point and doesn't anymore. Any chance this functionality can be implemented somehow?

Edit: I forgot to mention I also tried changing the timezone variable to see if that made a difference, but it didn't

**Comment by mikael-j-rich** [comment]
You can. Just set the COUNTRY_CODE env variable to for example Australia, and server list will filter on it. Worked for me anyways :)

**Comment by adamef93** [comment]
Thanks, but I'm trying to connect to a different state within my country, not a different country altogether

**Comment by veepee78** [comment]
I was not able to change country by using country_code. What should I write there? Name, country 2 letter code? 
It connected only to my country.

**Comment by jimbobjonesbob** [comment]
> I was not able to change country by using country_code. What should I write there? Name, country 2 letter code? It connected only to my country.

I was trying to get it to change server for awhile using COUNTRY_CODE but couldn't. Here is what I did. I commented out QUERY=filters\[servers_groups\]\[identifier\]=legacy_p2p, and put this in: QUERY=filters\[country_id\]=209

209 = switzerland. That works for me.

**Comment by adamef93** [comment]
Again, I'm trying to connect to a different state within the same country. Please see my last comment.

**Comment by jimbobjonesbob** [comment]
My reply was not in response to you, but if you read the thread I linked to
you'll find the info as to how to connect to a specific server.

Note END_POINT

**Comment by pirakleous** [comment]
@mikael-j-rich the latest docker image does not have the COUNTRY_CODE change. How did you get that to work?

**Comment by mikael-j-rich** [comment]
@pirakleous sorry, probably didn't check the latest version. I'm not running this image anymore for different reasons but i'll check if i have my latest compose file saved somewhere.

**Comment by Joly0** [comment]
Btw, i think the COUNTRY_CODE variable doesnt work atm. I tried to run this [line](https://github.com/bubuntux/nordlynx/blob/2fb80256d1daeed2d8dd450aa8bce802a0e543bb/root/etc/services.d/wireguard/run#L10C7-L10C7) inside the container and it returned nothing. I used country_code 127 for switzerland
Maybe it would be useful to allow the country name aswell, since the country code seems to change (for others its 209 for me now its 127)

**Comment by battlesnake** [comment]
Similar.  Tried COUNTRY_CODE as Switzerland, but GeoIP still says Netherlands (where my server is located).

**Comment by landcraft** [comment]
I gave up and installed the NordVPN extension in the relevant browser container. Works like a charm.
