### ISSUE TITLE
Unable to select a server ¯\_(⊙︿⊙)_/¯

### ISSUE THREAD

**Issue by IamDan77** [bubuntux/nordlynx#164]
### **Describe the bug**
Not selecting a server. It was previously working without issue

### **To Reproduce using docker CLI**
Using Unraid so no CLI

### **Expected behavior**
Connect to a server as it used to

### **Logs**
`parse error: Invalid numeric literal at line 1, column 7
[migrations] started
[migrations] no migrations found
[2024-03-21T22:53:35+00:00] Firewall is up, everything has to go through the vpn
usermod: no changes
───────────────────────────────────────
  _____ __ __ _____ _____ _____ _____ 
 |     |  |  |   __|_   _|     |     |
 |   --|  |  |__   | | | |  |  | | | |
 |_____|_____|_____| |_| |_____|_|_|_|
       _____ __ __ _ __    ____  
      | __  |  |  | |  |  |    \ 
      | __ -|  |  | |  |__|  |  |
      |_____|_____|_|_____|____/ 

  Based on images from linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
Bubuntux: https://github.com/sponsors/bubuntux
WireGuard: https://www.wireguard.com/donations/
To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    911
User GID:    911
───────────────────────────────────────

[2024-03-22T09:53:35+11:00] Enabling connection to eth0 172.17.0.3/16
[2024-03-22T09:53:35+11:00] Enabling connection to secure interfaces
[2024-03-22T09:53:35+11:00] No interface network6 detected
[2024-03-22T09:53:35+11:00] Enabling connection to network 192.168.0.0/16
[custom-init] No custom files found, skipping...
[ls.io-init] done.
[2024-03-22T09:53:35+11:00] Finding the best server...
[2024-03-22T09:53:48+11:00] Unable to select a server ¯\_(⊙︿⊙)_/¯`

### **Additional context**
Using Unraid with the latest docker.

I was able to force an update and it worked and connected to a server temporarily. However once I restarted the container it threw this error again

**Comment by aaronmgriffin** [comment]
I am also seeing this issue

```
nordlynx  | [2024-06-22T03:24:40+00:00] Finding the best server...
nordlynx  | parse error: Invalid numeric literal at line 1, column 20
nordlynx  | [2024-06-22T03:24:47+00:00] Unable to select a server ¯\_(⊙︿⊙)_/¯
```

**Comment by janstadt** [comment]
Any ideas as to why this is happening?

**Comment by IamDan77** [comment]
No idea. At first I thought it was a rate limit. I left it for 24hours and got the same issue. I gave up and use GlueTUN instead. Its been flawless

**Comment by janstadt** [comment]
@IamDan77 I've been meaning to look into that. Set it up in 5 minutes and we're up and running. Thanks for the reminder!
