### ISSUE TITLE
Using country code won't change the server

### ISSUE THREAD

**Issue by Ansem93** [bubuntux/nordlynx#174]
### **Describe the bug**
I looked for the country ID using this link: https://api.nordvpn.com/v1/servers/countries
After I added the code ID I tried to use https://whatismyipaddress.com/ to check if I actually changed nation but I didn't
In my case I choose Croatia and so I added the ID 54

### **Expected behavior**
After adding the ID code I expect that it would choose a server from that nation

### **Additional context**
If it's not possible to choose the country like that it should be updated the readme with the correct way to select a country/server

**Comment by NewNork** [comment]
I second that. Setting the environment variable

`CONNECT=some_country`

isn't working either. I had a dig around a bit and found some renaming of environment variables. they didn't have any effect either. Forcing a specific IP, which I got from above mentioned API, won't work, it reports a port error.

**Comment by NewNork** [comment]
Actually, building the container from this repository, everything works as expected. I had to 

`chmod -R 700 etc/`

before 

`docker build -t bubuntux/nordlynx .`

Also, I tested it with a newer version (3.20) of the base image (the used 3.17 is deprecated) and it seems to work fine.

I reckon the current branch never made it to the Docker Hub.

**Comment by Ansem93** [comment]
In the end I just switched container and moved to tmknight88/nordvpn since it's based on the official linux client
