### ISSUE TITLE
Unable to login to get PRIVATE_KEY

### ISSUE THREAD

**Issue by lownignitus** [bubuntux/nordlynx#33]
### **Describe the bug**
I keep trying to use various usernames/passwords to get private key to setup docker and am not able to get it to login.

### **To Reproduce using docker CLI**
Full command needs to be provided (hide credentials)
`docker run --rm --cap-add=NET_ADMIN --cap-add=NET_RAW -e USER=XXX -e PASS=YYY bubuntux/nordvpn nord_private_key `

### **Expected behavior**
Expected to login and get my private key

### **Logs**
>[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] docker_utils: applying...
[fix-attrs.d] docker_utils: exited 0.
[fix-attrs.d] nord_utils: applying...
[fix-attrs.d] nord_utils: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-firewall: executing...
Firewall is up, everything has to go through the vpn
[cont-init.d] 00-firewall: exited 0.
[cont-init.d] 10-tun: executing...
[cont-init.d] 10-tun: exited 0.
[cont-init.d] 20-inet: executing...
Enabling connection to secure interface and docker network
[cont-init.d] 20-inet: exited 0.
[cont-init.d] 20-inet6: executing...
No inet6 network
[cont-init.d] 20-inet6: exited 0.
[cont-init.d] 30-route: executing...
[cont-init.d] 30-route: exited 0.
[cont-init.d] 30-route6: executing...
[cont-init.d] 30-route6: exited 0.
[cont-init.d] 40-allowlist: executing...
[cont-init.d] 40-allowlist: exited 0.
[cont-init.d] done.
[services.d] starting services
2022/02/10 06:08:21 [Info] Daemon has started
2022/02/10 06:08:21 Kill Switch set to: disabled
NordVPN App Connection Settings:
Technology: OPENVPN
Protocol: UDP
Firewall: enabled
KillSwitch: disabled
Obfuscate: disabled
CyberSec: disabled
DNS:
IPv6: disabled
Notify: disabled
Auto-connect: disabled
2022/02/10 06:08:21 Auto-connect set to: disabled
NordVPN App Connection Settings:
Technology: OPENVPN
Protocol: UDP
Firewall: enabled
KillSwitch: disabled
Obfuscate: disabled
CyberSec: disabled
DNS:
IPv6: disabled
Notify: disabled
Auto-connect: disabled
2022/02/10 06:08:21 DNS set to: disabled
NordVPN App Connection Settings:
Technology: OPENVPN
Protocol: UDP
Firewall: enabled
KillSwitch: disabled
Obfuscate: disabled
CyberSec: disabled
DNS:
IPv6: disabled
Notify: disabled
Auto-connect: disabled
2022/02/10 06:08:21 CyberSec set to: disabled
NordVPN App Connection Settings:
Technology: OPENVPN
Protocol: UDP
Firewall: enabled
KillSwitch: disabled
Obfuscate: disabled
CyberSec: disabled
DNS:
IPv6: disabled
Notify: disabled
Auto-connect: disabled
2022/02/10 06:08:21 Protocol set to: UDP
NordVPN App Connection Settings:
Technology: OPENVPN
Protocol: UDP
Firewall: enabled
KillSwitch: disabled
Obfuscate: disabled
CyberSec: disabled
DNS:
IPv6: disabled
Notify: disabled
Auto-connect: disabled
2022/02/10 06:08:21 IPv6 set to: disabled
NordVPN App Connection Settings:
Technology: OPENVPN
Protocol: UDP
Firewall: enabled
KillSwitch: disabled
Obfuscate: disabled
CyberSec: disabled
DNS:
IPv6: disabled
Notify: disabled
Auto-connect: disabled
2022/02/10 06:08:21 Technology set to: OPENVPN
NordVPN App Connection Settings:
Technology: OPENVPN
Protocol: UDP
Firewall: enabled
KillSwitch: disabled
Obfuscate: disabled
CyberSec: disabled
DNS:
IPv6: disabled
Notify: disabled
Auto-connect: disabled
2022/02/10 06:08:21 Get "https://zwyr157wwiu6eior.com/v1/helpers/ips/insights": quic: performing request: curl: Couldn't connect to server
[services.d] done.
-2022/02/10 06:08:25 [Error] logging in: Bad Request: Invalid username
Username or password is not correct. Please try again.
Invalid Username or password.
2022/02/10 06:08:25 Technology set to: NORDLYNX
NordVPN App Connection Settings:
Technology: NORDLYNX
Protocol: UDP
Firewall: enabled
KillSwitch: disabled
Obfuscate: disabled
CyberSec: disabled
DNS:
IPv6: disabled
Notify: disabled
Auto-connect: disabled
Technology is successfully set to 'NORDLYNX'.
Subnet 172.17.0.0/16 is whitelisted successfully.
Connecting...
You are not logged in.
Unable to connect retrying in 1 seconds.
You are not logged in.
Unable to connect retrying in 2 seconds.
You are not logged in.
Unable to connect retrying in 4 seconds.
^C[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.<

I have tried both actual NordVPM login username and password, the Service Credentials login and password, and a mixture of them. Nothing I have done works,

**Comment by bubuntux** [comment]
this is a problem with the nordvpn container please file this bug there, also you can follow the manual instructions to obtain your private key https://forum.openwrt.org/t/instruction-config-nordvpn-wireguard-nordlynx-on-openwrt/89976
