### ISSUE TITLE
Connecting to specific server 

### ISSUE THREAD

**Issue by julio8a** [bubuntux/nordlynx#39]
**Is your feature request related to a problem? Please describe.**
More of a question...

I migrated from bubuntux/nordvpn. In Nnordvpn, to connect to a server there was this env property:
`CONNECT=United_States`
However, there are no guidelines for connecting to a specific server in nordlynx. 

I notice there are different env property names across the repositories, i.e. 
In nordvpn adding a network was done like this:
`NETWORK=192.168.1.0/24  # So it can be accessed within the local network`

However, here (nordlynx) it's done like this:
`NET_LOCAL=192.168.1.0/24`

**Describe the solution you'd like**
Add to readme doc, how to connect to a specific server.

**Describe alternatives you've considered**
Continue to use `CONNECT=` ?

**Comment by b-kamphorst** [comment]
Hi @julio8a, welcome to NordLynx. You might be interested in [this discussion](https://github.com/bubuntux/nordlynx/discussions/28#discussioncomment-2115495), which explains how to use the `QUERY` environment variable that replaces (and generalizes) the `COUNTRY` one.
