### ISSUE TITLE
Does nordlynx container support a "killswitch" if connection drops?

### ISSUE THREAD

**Issue by Raemsna** [bubuntux/nordlynx#46]
**Is your feature request related to a problem? Please describe.**
If connection drops, I would like to have the possibility to choose upfront, if
1) the connected containers still can access internet or
2) the connected containers can NOT access internet until connection to nordlynx is reconnected

**Describe the solution you'd like**
have the possibility to choose upon container start, if there is a killswitch (2) or not (1)

Thank you very much for your work on this! Highly appreciate it! 
Raemsna

**Comment by yash-fn** [comment]
I think I remember this being asked somewhere else and the answer was that killswitch is not neccesary due to the iptables rules that are set that prevent any connections from leaking out. So basically killswitch is always active and you can't disable it.

**Comment by bubuntux** [comment]
@yash-fn  that is correct, killswitch is enable by default using iptables, you can disable it using the POST_DOWN

**Comment by fbacker** [comment]
Are we sure about this?
I noticed by accident that a container that is using nordlynx as passthrough had my ISP public address. Everything looked to be working, I had to restart nordlynx to get the vpn ip address again. Couldn't see anything from logs that vpn had issues.

**Comment by fbacker** [comment]
Got same issue today, however doesn't seem to be nordlynx container.
Checked the nordlynx logs, did a curl ipconfig.io inside the container and here the ip is correct.
However checking the ip on another container it shows the public ip.

Using docker-compose with portainer so might be some issue here instead that goes outside the vpn in some scenarios.

myservice:
  depends_on:
      - vpn
   network_mode: "service:vpn"
