### ISSUE TITLE
Support MFA to get the private

### ISSUE THREAD

**Issue by damccull** [bubuntux/nordlynx#48]
You have a really cool image to get the nordlynx private key but it doesn't seem to support mfa. Please make it drop us into an interactive prompt to use  nordvpn login and enter our credentials manually.

**Comment by bubuntux** [comment]
the request is outside of the scope of this image, and that is something you can do already `docker run --rm --ti .... nordvpn:get_private_key bash ` now you have a shell on which you can 

#start the service
`/usr/sbin/nordvpnd > /dev/null &`
# login
`nordvpn login`
# make sure you are using nordlynx
`nordvpn set technology NordLynx`
# conect
`nordvpn connect`
# get the key
`wg show nordlynx private-key`


you can take a look at what the image does here https://github.com/bubuntux/nordvpn/blob/get_private_key/get_private_key.sh for reference

**Comment by JoshKeegan** [comment]
For anyone else needing to do this, here's the full list of commands I needed to run to do this (combination of the post above, linked script & a small addition for handling the callback once auth is complete in the browser)

```bash
docker run --rm -it --cap-add=NET_ADMIN --entrypoint bash bubuntux/nordvpn:get_private_key

mkdir -p /dev/net
mknod -m 0666 /dev/net/tun c 10 200
mkdir -m 0770 /run/nordvpn

/usr/sbin/nordvpnd > /dev/null &

# wait a sec for svc to start, then carry on
nordvpn login
```
Copy link & continue in web browser. Once logged in, don't click the continue button but instead copy the address and extract the `exchange_token` param. Decode it (last 2 chars will be `%3D%3D` which is `==`). 

```bash
# Replace TOKEN with your exhange_token from above
nordvpn login --callback nordvpn://login?exchange_token=TOKEN

nordvpn set technology NordLynx
nordvpn connect
wg show nordlynx private-key
nordvpn disconnect
```
