### ISSUE TITLE
Enviroment Variables

### ISSUE THREAD

**Issue by beltet** [bubuntux/nordlynx#59]
Hi!
With the old container you could use different variables to get it to connect to different countries or if I wanted P2P.
Tried it with the same variables but with no success. What is the new ones?

**Comment by michaelkrieger** [comment]
See the [NordVPN Cheat Sheet](https://sleeplessbeastie.eu/2019/02/18/how-to-use-public-nordvpn-api/)

A full list of country IDs can be obtained via

```
curl --silent "https://api.nordvpn.com/v1/servers/countries" | jq --raw-output '.[] | [.id, .name] | @tsv'
```

Some examples (uncomment as required) to put into a docker-compose file...
```
      #- QUERY=filters\[country_id\]=228     # United States
      #- QUERY=filters\[country_id\]=228&\[servers_groups\]\[identifier\]=legacy_p2p       # USA P2P
      #- QUERY=filters\[country_id\]=38       # Canada
      #- QUERY=filters\[country_id\]=13      # Australia
```
