### ISSUE TITLE
ifelse: fatal: unable to exec nord_private_key: No such file or directory

### ISSUE THREAD

**Issue by Dim3333** [bubuntux/nordlynx#68]
Hello,

I launch this command:
`docker run --rm --cap-add=NET_ADMIN --cap-add=NET_RAW -e USER=XXX -e PASS=YYY bubuntux/nordvpn nord_private_key`

and obtain that:

`
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] docker_utils: applying...
[fix-attrs.d] docker_utils: exited 0.
[fix-attrs.d] nord_utils: applying...
[fix-attrs.d] nord_utils: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-firewall: executing...
Firewall is up, everything has to go through the vpn
[cont-init.d] 00-firewall: exited 0.
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing...
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing...
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Bubuntux: https://github.com/sponsors/bubuntux
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 10-tun: executing...
[cont-init.d] 10-tun: exited 0.
[cont-init.d] 20-inet: executing...
Enabling connection to secure interface and docker network
[cont-init.d] 20-inet: exited 0.
[cont-init.d] 20-inet6: executing...
No inet6 network
[cont-init.d] 20-inet6: exited 0.
[cont-init.d] 30-route: executing...
[cont-init.d] 30-route: exited 0.
[cont-init.d] 30-route6: executing...
[cont-init.d] 30-route6: exited 0.
[cont-init.d] 40-allowlist: executing...
[cont-init.d] 40-allowlist: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
ifelse: fatal: unable to exec nord_private_key: No such file or directory
[cmd] nord_private_key exited 127
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
`

**Comment by axeldna** [comment]
Hey,

I'm also trying to troubleshoot this issue to get the private key. I think you have to try with: `bubuntux/nordvpn:get_private_key` instead of the command specified in the docker hub page (GitHub page has the updated command).

What I'm facing now is something like the following:
```
Whoops! /run/nordvpn/nordvpnd.sock not found
Invalid Username or password.
```

**Comment by Dim3333** [comment]
Effectively, same issue, what's the solution ?

`Status: Downloaded newer image for bubuntux/nordvpn:get_private_key
A new version of NordVPN is available! Please update the application.
It's not you, it's us. We're having trouble reaching our servers. If the issue persists, please contact our customer support.
Invalid Username or password.
`

**Comment by axl7777** [comment]
I succesfully used instructions from here:
[https://gist.github.com/bluewalk/7b3db071c488c82c604baf76a42eaad3](https://gist.github.com/bluewalk/7b3db071c488c82c604baf76a42eaad3
)
A little cumbersome (you need to install wireguard), but it worked for me.

**Comment by Dim3333** [comment]
Thanks @axl7777  but see here : [https://github.com/bubuntux/nordlynx/issues/71](url)
